config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root 'pages#home'
  get 'contactus' => 'pages#contactus'
  get 'signup' => 'devise/registrations#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject = nil)
		user && user.admin?
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlatineV0</title>
    <meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>Platine</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="body" class="body-wrapper boxed-menu" >
    <div class="page-loader" style="background: url(<%= asset_path 'preloader.gif' %>) center no-repeat #fff;"></div> 
    <!-- Preloader -
    <div id="preloader" class="smooth-loader-wrapper">
      <div class="smooth-loader">
        <div class="loader1">
        <div class="loader-target">
          <div class="loader-target-main"></div>
          <div class="loader-target-inner"></div>
          </div>
        </div>
      </div>
    </div> 
-->

  <!-- Flash Messages -->
  <% flash.each do |name, message|%>
   <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
  <% end %>

    <%= yield %>

  </body>
   <!-- FOOTER -->
    <footer style="background-image: url(<%= asset_path 'background/bg-footer.jpg' %>) ;">
      <!-- FOOTER INFO -->
      <div class="clearfix footerInfo">
        <div class="container">
          <div class="row">
            <div class="col-sm-3 col-xs-12">
              <div class="footerText">
                <a class="footerLogo" href="<%= root_path %>">
                  <img src="<%= asset_path 'logo/logo-blanc.svg' %>" height="44px" width="140px" />
                </a>
                <ul class="list-styled list-contact">
                  <li><i class="fa fa-phone" aria-hidden="true"></i>[88] 657 524 332</li>
                  <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">info@listy.com</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-3 col-xs-12">
              <div class="clearfix copyRight">
              <ul class="list-inline socialLink">
                      <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                      <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                      <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
              </ul>
            </div>
            </div>
            <div class="col-sm-3 col-xs-12">
              <div class="footerInfoTitle">
                <h4>Liens</h4>
              </div>
              <div class="useLink">
                <ul class="list-unstyled">
                  <li><a href="dashboard.html">Lien 1</a></li>
                  <li><a href="sign-up.html">Lien 2</a></li>
                  <li><a href="login.html">Lien 3</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-3 col-xs-12">
              <div class="footerInfoTitle">
                <h4>Notre société</h4>
              </div>
              <div class="useLink">
                <ul class="list-unstyled">
                  <li><%= link_to "Nous contacter", contactus_path %></li>
                  <li><a href="sign-up.html">Lien 2</a></li>
                  <li><a href="login.html">Lien 3</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- COPY RIGHT -->
      <div class="clearfix copyRight">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="copyRightWrapper">
                <div class="row">
                    <div class="copyRightText">
                      <p>Copyright &copy; 2018. All Rights Reserved by Platine</a></p>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>



 

</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We're working on our One Month Rails Rails project.</p>
<div id="preloader" class="smooth-loader-wrapper">
    <div class="smooth-loader">
      <div class="loader1">
      <div class="loader-target">
        <div class="loader-target-main"></div>
        <div class="loader-target-inner"></div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/contactus.html.erb
<%= render 'shared/navbar_standard' %>

<!-- PAGE TITLE SECTION -->
<section class="clearfix pageTitleSection bg-image" style="background-image: url(<%= asset_path 'background/bg-contactus.jpg' %>);">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="pageTitle">
					<h2>Nous contacter</h2>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- CONTACT SECTION -->
<section class="clearfix">
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-xs-12">
				<div class="contactInfo">
					<ul class="list-unstyled list-address">
						<li>
							<i class="fa fa-map-marker" aria-hidden="true"></i>
							12 rue Fosh <br> 75016 Paris
						</li>
						<li>
							<i class="fa fa-phone" aria-hidden="true"></i>
							+33 6045241
						</li>
						<li>
							<i class="fa fa-envelope" aria-hidden="true"></i>
							<a href="#">info@platine.com</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-sm-8 col-xs-12">
				<div class="signUpFormArea">
					<div class="priceTableTitle">
						<h2>Des questions?</h2>
						<p>N'hésitez pas à nous envoyer vos questions via ce formulaire, nous vous répondrons avec plaisir !</p>
					</div>
					<div class="signUpForm">
						<form action="#" method="">
							<div class="formSection">
								<div class="row">
									<div class="form-group col-sm-6 col-xs-12">
										<label for="selectSome" class="control-label">Sujet*</label>
										<div class="contactSelect">
											<select name="guiest_id8" id="guiest_id8" class="select-drop">
												<option value="0">-- Selectionnez un sujet--</option>
												<option value="1">Je suis artiste, je veux plus d'infos</option>
												<option value="2">Je suis futur marié, je veux plus d'infos</option>
												<option value="3">Autres</option>            
											</select>
										</div>
									</div>
									<div class="form-group col-sm-6 col-xs-12">
										<label for="companyName" class="control-label">Nom de votre société</label>
										<input type="text" class="form-control" id="companyName">
									</div>
									<div class="form-group col-sm-12 col-xs-12">
										<label for="yourName" class="control-label">Votre nom*</label>
										<input type="text" class="form-control" id="yourName">
									</div>
									<div class="form-group col-sm-12 col-xs-12">
										<label for="emailAddress" class="control-label">Votre email*</label>
										<input type="email" class="form-control" id="emailAddress">
									</div>
									<div class="form-group col-sm-12 col-xs-12">
										<label for="textBox" class="control-label">Votre demande*</label>
										<textarea class="form-control" rows="3"></textarea>
									</div>
									<div class="form-group col-sm-12 col-xs-12 mb0">
										<button type="submit" class="btn btn-primary">Envoyer</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<%= render 'shared/navbar_homepage' %>

<!-- BANNER SECTION -->
<section  class="clearfix homeBanner"  style="background-image: url(<%= asset_path 'banner/banner1.jpg' %>) ; ">  
  <div class="container">
    <div class="row">
      <div class="col   -xs-12">
        <div class="banerInfo">
          <h1>Mettons en musique</h1>
          <h1>le plus beau jour de votre vie</h1>
          <form class="form-inline" action="listing-sidebar-map-left.html" method="">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">Date</div>
                <input type="text" class="form-control" id="findItem" placeholder="Jour de votre mariage">
                <div class="input-group-addon addon-right"></div>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">Lieu</div>
                <input type="text" class="form-control" id="nearLocation" placeholder="Dans quelle ville?">
                <div class="input-group-addon addon-right"><i class="icon-listy icon-target" aria-hidden="true"></i></div>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Chercher <i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- INTEREST SECTION -->
<section class="clearfix interestArea">
  <div class="container">
    <div class="page-header text-center">
      <h2>Que recherchez vous ?</h2>
    </div>
    <div class="row">
      <div class="col-sm-4 col-xs-12">
        <div class="thingsBox">
          <div class="thingsImage">
            <img src="<%= asset_path 'catego/dj.jpg' %>" alt="DJ">
              <div class="thingsMask">
                <a href="listing-details-left.html"><h2>DJ</h2></a>
              </div>
          </div>
        </div>
       </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thingsBox">
          <div class="thingsImage">
            <img src="<%= asset_path 'catego/singer.jpg' %>" alt="Chanteur">
              <div class="thingsMask">
                <a href="listing-details-left.html"><h2>Chanteur</h2></a>
              </div>
          </div>
        </div>
       </div>
       <div class="col-sm-4 col-xs-12">
        <div class="thingsBox">
          <div class="thingsImage">
            <img src="<%= asset_path 'catego/band.jpg' %>" alt="Groupe">
              <div class="thingsMask">
                <a href="listing-details-left.html"><h2>Groupe</h2></a>
              </div>
          </div>
        </div>
       </div>
    </div>
  </div>
</section>

app/views/shared/_navbar_homepage.html.erb
<!-- HEADER -->
<div class="main-wrapper"> 

    <header id="pageTop" class="header">

      <!-- TOP INFO BAR -->
      <div class="nav-wrapper" >
        <nav id="menuBar" class="navbar navbar-default transparent-navbar " role="navigation"> 
          <a class="navbar-brand" href="<%= root_path %>">          
            <img src="<%= asset_path 'logo/logo-blanc.svg' %>" height="44px" width="140px" />
          </a>

<% if user_signed_in? %>

            <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn'%>
            

<% else %>   
              <%= button_to "Se connecter", new_user_session_path, class: 'btn btn-default navbar-btn' %>
            
            
         
<% end %>

        </nav>
      </div>

    </header>
</div>

app/views/shared/_navbar_standard.html.erb
<div class="main-wrapper">
  <!-- HEADER -->
  <header id="pageTop" class="header">

    <!-- TOP INFO BAR -->

    <div class="nav-wrapper navbarWhite">
      <!-- NAVBAR -->
      <nav id="menuBar" class="navbar navbar-default lightHeader animated " role="navigation">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">

            <a class="navbar-brand" href="<%= root_path %>">
            <img src="<%= asset_path 'logo/logo-blanc.svg' %>" height="44px" width="140px" />
            </a>
<% if user_signed_in? %>

            <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn'%>
            

<% else %>   
              <%= button_to "Se connecter", new_user_session_path, class: 'btn btn-default navbar-btn' %>
            
            
         
<% end %>
         </div> 
      </nav>
    </div>
  </header>
</div>

app/views/shared/_navbar_without_login.html.erb
<div class="main-wrapper">
  <!-- HEADER -->
  <header id="pageTop" class="header">

    <!-- TOP INFO BAR -->

    <div class="nav-wrapper navbarWhite">
      <!-- NAVBAR -->
      <nav id="menuBar" class="navbar navbar-default lightHeader animated " role="navigation">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">

            <a class="navbar-brand" href="<%= root_path %>">
            <img src="<%= asset_path 'logo/logo-blanc.svg' %>" height="44px" width="140px" />
            </a>

         </div> 
      </nav>
    </div>
  </header>
</div>